- hosts: all
  become: yes
  vars:
    user: akiyama-k
  tasks:   
    - name: Set timezone
      timezone: name=Asia/Tokyo

    - name: Install packages
      apt: name={{item}} state=present update_cache=yes
      with_items:
        - fish
        - docker
        - emacs
        - vim
        - git
        - wget
        - curl
        - tig
        - python3
        - fonts-powerline
        
    - name: Execute git clone dotfiles
      become_user: '{{user}}'
      git: repo=https://github.com/itouri/dotfiles.git dest=/home/{{user}}/dotfiles accept_hostkey=yes

    - name: Setup dotfiles
      become_user: '{{user}}'
      command: bash setup.sh chdir=/home/{{user}}/dotfiles
    
    # - name: Execute git clone goenv
    #   become_user: '{{user}}'
    #   git: repo=https://github.com/syndbg/goenv.git dest=/home/{{user}}/.goenv accept_hostkey=yes

    - name: Install fisherman
      shell: curl -Lo ~/.config/fish/functions/fisher.fish --create-dirs git.io/fisher

    - name: Clone fzf
      git:
        repo: https://github.com/junegunn/fzf.git
        dest: /home/{{user}}/.fzf

    - name: Install fzf
      shell: /home/{{user}}/.fzf/install --all

    - name: clone vim bundle
      git: repo=https://github.com/VundleVim/Vundle.vim.git dest=/home/{{user}}/.vim/bundle/Vundle.vim

    - name: Install vim bandle
      shell: vim +PluginInstall +qall

    #TODO pip install

    - name: go gets
      shell: go get github.com/motemen/ghq

    - name: copy config.fish
      shell: cp config.fish /home/{{user}}/.config/fish

    #TODO fool
    - name: Install fisher plugin
      shell: fish -c "fisher add jethrokuan/z" && fish -c "fisher add decors/fish-ghq" && fish -c "fisher add oh-my-fish/theme-bobthefish"

    - name: Clone powerline fonts
      git: repo=https://github.com/powerline/fonts.git dest=/home/{{user}}/fonts

    - name: Install powerline fonts
      shell: /home/{{user}}/fonts/install.sh && rm -rf /home/{{user}}/fonts

    # - name: source bashrc
    #   shell: source /home/{{user}}/.bashrc
    