- hosts: all
  become: yes
  vars:
    #TODO
    user: vagrant
  tasks:   
    - name: Set timezone
      timezone: name=Asia/Tokyo

    - name: Install apt packages
      apt: name={{item}} state=present update_cache=yes
      with_items:
        - fish
        - docker
        - emacs
        - vim
        - git
        - wget
        - curl
        - tig
        - python3
        - fonts-powerline
        - golang-go

    - name: Setup dotfiles
      become_user: '{{user}}'
      command: bash setup.sh chdir=/home/{{user}}/dotfiles

    - name: Clone fzf
      git:
        repo: https://github.com/junegunn/fzf.git
        dest: /home/{{user}}/.fzf

    - name: Install fzf
      shell: /home/{{user}}/.fzf/install --all

    - name: clone vim bundle
      git: repo=https://github.com/VundleVim/Vundle.vim.git dest=/home/{{user}}/.vim/bundle/Vundle.vim

    - name: Install vim bandle
      shell: vim +PluginInstall +qall

    #TODO pip install

    - name: export gopath
      shell: export GOPATH=/home/{{user}}/go

    - name: go gets
      shell: go get github.com/motemen/ghq

    - name: Clone powerline fonts
      git: repo=https://github.com/powerline/fonts.git dest=/home/{{user}}/fonts

    - name: Install powerline fonts
      shell: /home/{{user}}/fonts/install.sh && rm -rf /home/{{user}}/fonts

    - name: Create fisherman directory
      file:
        path: /home/{{user}}/.config/fish/functions
        owner: vagrant
        group: vagrant
        mode: 0755
        state: directory

    - name: Install fisherman
      get_url:
        url: https://git.io/fisher
        dest: /home/{{user}}/.config/fish/functions/fisher.fish
        
    #TODO fool
    #- name: Install fisher plugin
    #  shell: fish -c "fisher add jethrokuan/z" && fish -c "fisher add decors/fish-ghq" && fish -c "fisher add oh-my-fish/theme-bobthefish"

    - name: copy config.fish
      copy:
        src: config.fish
        dest: /home/{{user}}/.config/fish
